apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
replicas: 5
selector:
    matchLabels:
    app: wordpress
template:
    metadata:
    labels:
        app: wordpress
    spec:
    containers:
      - name: wordpress
        image: wordpress
        ports:
            - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: database-1.c54kymgywo1k.us-east-1.rds.amazonaws.com
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: wordpress
          - name: WORDPRESS_DB_NAME
            value: wordpress
        volumeMounts:
          - name: nfs
            mountPath: /mnt/wordpress
    volumes:
      - name: nfs
        persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
selector:
    app: wordpress
ports:
  - protocol: TCP
    port: 80
    targetPort: 80